"""Update budget schema for active budget constraints

Revision ID: 24ac67a15141
Revises: 6efce56d24e6
Create Date: 2025-09-07 21:28:48.389074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ac67a15141'
down_revision = '6efce56d24e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Set default values for existing records before making column non-nullable
    op.execute("UPDATE budgets SET is_active = false WHERE is_active IS NULL")
    
    op.alter_column('budgets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('false'))
    op.drop_constraint('budgets_year_key', 'budgets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('budgets_year_key', 'budgets', ['year'])
    op.alter_column('budgets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###