"""Add budget and budget_line_items tables

Revision ID: dce1dbc0680f
Revises: aaa4d1f48360
Create Date: 2025-09-07 19:12:35.248945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce1dbc0680f'
down_revision = 'aaa4d1f48360'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###